name: Api CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'api/**'

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './api/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: up docker container
        run: docker-compose up -d mongo
      - name: Run tests
        run: npm run test
