name: Node.js CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'demos/**'

defaults:
  run:
    working-directory: ./demos

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Run CI script
        run: yarn ci
      - name: Run tests
        run: yarn test
